Update ftppull.yml

diff --git a/.github/workflows/ftppull.yml b/.github/workflows/ftppull.yml
--- a/.github/workflows/ftppull.yml
+++ b/.github/workflows/ftppull.yml
@@ -97,12 +97,17 @@ jobs:
           fi
         done < local_files.txt
 
-    - name: Set up Git
+    - name: Verify .git directory and Configure Git
       run: |
-        echo "Setting up Git configuration"
-        git config --global user.email "actions@github.com"
-        git config --global user.name "GitHub Action"
-        git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ajinkyathail/htdocs.git
+        echo "Verifying .git directory and configuring Git"
+        if [ -d .git ]; then
+          git config --global user.email "actions@github.com"
+          git config --global user.name "GitHub Action"
+          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ajinkyathail/htdocs.git
+        else
+          echo ".git directory not found. Exiting."
+          exit 1
+        fi
 
     - name: Check for changes
       run: |
